### ISSUE TITLE
Does MonetDBLite-Python work on OSX?

### ISSUE THREAD

**Issue by mstump** [hannesmuehleisen/MonetDBLite-Python#28]
I've tried installations from pip (version ```0.6.0```) and I've compiled the library from scratch using ```master``` branch of the git repo (version ```0.6.2```). In both instances I'm using ```Python 3.7.1``` installed via homebrew.

When initializing a new disk backed database it'll fail after creating the directory. It looks like it's not able to load the supporting shared lib.

```
import monetdblite
import numpy
monetdblite.init('foobar')
monetdblite.create('foobar86', {'i': numpy.arange(10000)})
```

```
Traceback (most recent call last):
  File "monetdb_test.py", line 36, in <module>
    monetdblite.init('foobar')
  File "/usr/local/lib/python3.7/site-packages/monetdblite-0.6.2-py3.7-macosx-10.14-x86_64.egg/monetdblite/__init__.py", line 46, in init
    return embeddedmonetdb.init(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/monetdblite-0.6.2-py3.7-macosx-10.14-x86_64.egg/monetdblite/embeddedmonetdb.py", line 113, in init
    raise __throw_exception(str(retval) + ' in ' + str(directory))
  File "/usr/local/lib/python3.7/site-packages/monetdblite-0.6.2-py3.7-macosx-10.14-x86_64.egg/monetdblite/embeddedmonetdb.py", line 98, in __throw_exception
    raise exceptions.DatabaseError(str.replace('MALException:', ''))
monetdblite.exceptions.DatabaseError: Failed to initialize MonetDB: GDKinit() failed. in b'foobar'
```

When initializing a ```:memory``` database and creating a table it'll fail at table creation saying that the table exists for all permutations of table.
```
import monetdblite
import numpy
monetdblite.init(':memory:')
monetdblite.create('foobar86', {'i': numpy.arange(10000)})
```

```
Traceback (most recent call last):
  File "monetdb_test.py", line 49, in <module>
    print("json", benchmark(stmt=monetdb_insert, number=number))
  File "monetdb_test.py", line 23, in benchmark
    raw_timings = t.repeat(repeat, number)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/timeit.py", line 204, in repeat
    t = self.timeit(number)
  File "/usr/local/Cellar/python/3.7.1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/timeit.py", line 176, in timeit
    timing = self.inner(it, self.timer)
  File "<timeit-src>", line 6, in inner
  File "monetdb_test.py", line 41, in monetdb_insert
    monetdblite.create('foobar86', {'i': numpy.arange(10000)})
  File "/usr/local/lib/python3.7/site-packages/monetdblite-0.6.2-py3.7-macosx-10.14-x86_64.egg/monetdblite/__init__.py", line 62, in create
    return embeddedmonetdb.create(*args, **kwargs)
  File "/usr/local/lib/python3.7/site-packages/monetdblite-0.6.2-py3.7-macosx-10.14-x86_64.egg/monetdblite/embeddedmonetdb.py", line 222, in create
    sql(query, client=client)
  File "/usr/local/lib/python3.7/site-packages/monetdblite-0.6.2-py3.7-macosx-10.14-x86_64.egg/monetdblite/embeddedmonetdb.py", line 140, in sql
    raise __throw_exception(str(retval))
  File "/usr/local/lib/python3.7/site-packages/monetdblite-0.6.2-py3.7-macosx-10.14-x86_64.egg/monetdblite/embeddedmonetdb.py", line 98, in __throw_exception
    raise exceptions.DatabaseError(str.replace('MALException:', ''))
monetdblite.exceptions.DatabaseError: SQL Query Failed: ParseException:SQLparser:42S01!CREATE TABLE: name 'foobar86' already in use
```

**Comment by mstump** [comment]
pffff, i take it back ```init``` works for disks if you supply an absolute path. ```:memory:``` still doesn't work.
